import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/ui/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        blue: {
          light: "#E6EFFF",
          light_hover: "#D9E6FF",
          light_active: "#B0CCFF",
          normal: "#005AFF",
          normal_hover: "#0051E6",
          normal_active: "#7D7D7D",
          dark: "#0044BF",
          dark_hover: "#003699",
          dark_active: "#002873",
          darker: "#002873",
        },
        red: {
          light: "#FDE6E9",
          light_hover: "#FDDADF",
          light_active: "#FAB2BC",
          normal: "#EF0627",
          normal_hover: "#D70523",
          normal_active: "#BF051F",
          dark: "#B3051D",
          dark_hover: "#8F0417",
          dark_active: "#6C0312",
          darker: "#54020E",
        },
        green: {
          light: "#E6FAED",
          light_hover: "#D9F7E4",
          light_active: "#B1EFC6",
          normal: "#02CA48",
          normal_hover: "#02B641",
          normal_active: "#02A23A",
          dark: "#029836",
          dark_hover: "#01792B",
          dark_active: "#015B20",
          darker: "#014719",
        },
        grey: {
          light: "#F5F5F5",
          light_hover: "#F0F0F0",
          light_active: "#E0E0E0",
          light_inactive: "#D9D9D9",
          normal: "#9C9C9C",
          normal_hover: "#8C8C8C",
          normal_active: "#7D7D7D",
          dark: "#757575",
          dark_hover: "#5E5E5E",
          dark_active: "#464646",
          darker: "#373737",
        },
        orange: {
          light: "#FFEFE8",
          light_hover: "#FFE7DC",
          light_active: "#FFCDB6",
          normal: "#FF5F15",
          normal_hover: "#E65613",
          normal_active: "#CC4C11",
          dark: "#BF4710",
          dark_hover: "#99390D",
          dark_active: "#732B09",
          darker: "#592107",
        },
      },
    },
  },
  plugins: [],
};
export default config;
