import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { Toast } from "@/ui";
import Reduxprovider from "@/store/redux-provider";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Goziri - ADMIN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className} suppressHydrationWarning={true}>
        <Reduxprovider>
          <Toast>{children}</Toast>
        </Reduxprovider>
      </body>
    </html>
  );
}
